global:
  marketplace-ami: true
  owner: quickstart-eng@amazon.com
  qsname: quickstart-confluent-kafka
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
tests:
  test1:
    parameter_input: enterprise-3.1.1-brokersonly-ondemand-ephemeral-centos.json
    regions:
      - ap-northeast-1
      - ap-northeast-2
      - ap-south-1
    template_file: confluent-kafka-master.template
  test2:
    parameter_input: enterprise-3.1.1-brokerszookeepers-ondemand-ephemeral-centos.json
    regions:
      - ap-southeast-1
      - ap-southeast-2
      - ca-central-1
    template_file: confluent-kafka-master.template
  test3:
    parameter_input: enterprise-3.2.0-brokersworkerszookeepers-ondemand-ephemeral-ubuntu.json
    regions:
      - eu-central-1
      - eu-west-1
      - eu-west-2
      - sa-east-1
    template_file: confluent-kafka-master.template
  test4:
    parameter_input: enterprise-3.1.2-brokersworkerszookeepers-spot-ebs-amzn.json
    regions:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
    template_file: confluent-kafka-master.template
